[package]
name = "adder"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0", git = "https://github.com/paritytech/ink", branch = "master", default-features = false }
ink_metadata = { version = "3.0.0", git = "https://github.com/paritytech/ink", branch = "master", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0", git = "https://github.com/paritytech/ink", branch = "master", default-features = false }
ink_storage = { version = "3.0.0", git = "https://github.com/paritytech/ink", branch = "master", default-features = false }
ink_lang = { version = "3.0.0", git = "https://github.com/paritytech/ink", branch = "master", default-features = false }

accumulator = { version = "3.0.0", git = "https://github.com/paritytech/ink", branch = "master", default-features = false, features = ["ink-as-dependency"] }

scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
scale-info = { version = "0.3", default-features = false, features = ["derive"], optional = true }

[lib]
name = "adder"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",

    "accumulator/std",
]
ink-as-dependency = []
